#!/usr/bin/env bash

declare -x GITHUB_TOKEN
: "${GITHUB_TOKEN:=""}"

declare -x PHP_LISTEN_MODE
: "${PHP_LISTEN_MODE:="0660"}"

declare -x PHP_PING_PATH
: "${PHP_PING_PATH:="/ping"}"

declare -x PHP_PING_RESPONSE
: "${PHP_PING_RESPONSE:="pong"}"

declare -x PHP_STATUS_PATH
: "${PHP_STATUS_PATH:="/status"}"

declare -x PHP_STATUS_LISTEN
: "${PHP_STATUS_LISTEN:="0.0.0.0:9001"}"

declare -x PHP_OUTPUT_BUFFERING
: "${PHP_OUTPUT_BUFFERING:="4096"}"

declare -x PHP_EXPOSE_HEADER
: "${PHP_EXPOSE_HEADER:="On"}"

declare -x PHP_ENABLE_DL
: "${PHP_ENABLE_DL:="Off"}"

declare -x PHP_MEMORY_LIMIT
: "${PHP_MEMORY_LIMIT:="1G"}"

declare -x PHP_ERROR_REPORTING
: "${PHP_ERROR_REPORTING:="E_ALL & ~E_DEPRECATED & ~E_STRICT"}"

declare -x PHP_DISPLAY_ERRORS
: "${PHP_DISPLAY_ERRORS:="On"}"

declare -x PHP_DISPLAY_STARTUP_ERRORS
: "${PHP_DISPLAY_STARTUP_ERRORS:="On"}"

declare -x PHP_ERROR_LOG
: "${PHP_ERROR_LOG:="/proc/self/fd/2"}"

declare -x PHP_LOG_ERRORS
: "${PHP_LOG_ERRORS:="On"}"

declare -x PHP_LOG_ERRORS_MAX_LEN
: "${PHP_LOG_ERRORS_MAX_LEN:="1024"}"

declare -x PHP_IGNORE_REPEATED_ERRORS
: "${PHP_IGNORE_REPEATED_ERRORS:="Off"}"

declare -x PHP_IGNORE_REPEATED_SOURCE
: "${PHP_IGNORE_REPEATED_SOURCE:="Off"}"

declare -x PHP_REPORT_MEMLEAKS
: "${PHP_REPORT_MEMLEAKS:="On"}"

declare -x PHP_TRACK_ERRORS
: "${PHP_TRACK_ERRORS:="Off"}"

declare -x PHP_HTML_ERRORS
: "${PHP_HTML_ERRORS:="On"}"

declare -x PHP_POST_MAX_SIZE
: "${PHP_POST_MAX_SIZE:="2G"}"

declare -x PHP_UPLOAD_MAX_FILESIZE
: "${PHP_UPLOAD_MAX_FILESIZE:="2G"}"

declare -x PHP_MAX_FILE_UPLOADS
: "${PHP_MAX_FILE_UPLOADS:="20"}"

declare -x PHP_MAX_EXECUTION_TIME
: "${PHP_MAX_EXECUTION_TIME:="3600"}"

declare -x PHP_MAX_INPUT_TIME
: "${PHP_MAX_INPUT_TIME:="3600"}"

declare -x PHP_ALLOW_URL_FOPEN
: "${PHP_ALLOW_URL_FOPEN:="On"}"

declare -x PHP_ALLOW_URL_INCLUDE
: "${PHP_ALLOW_URL_INCLUDE:="Off"}"

declare -x PHP_DATE_TIMEZONE
: "${PHP_DATE_TIMEZONE:="UTC"}"

declare -x PHP_LOG_LEVEL
: "${PHP_LOG_LEVEL:="warning"}"

declare -x PHP_MAX_CHILDREN
: "${PHP_MAX_CHILDREN:="75"}"

declare -x PHP_MAX_REQUESTS
: "${PHP_MAX_REQUESTS:="500"}"

declare -x PHP_PROCESS_IDLE_TIMEOUT
: "${PHP_PROCESS_IDLE_TIMEOUT:="10s"}"

declare -x PHP_COMPOSER_INSTALL
: "${PHP_COMPOSER_INSTALL:="true"}"

declare -x PHP_WEBROOT
: "${PHP_WEBROOT:="/srv/www"}"

declare -x PHP_COMPOSER_ROOT
: "${PHP_COMPOSER_ROOT:="${PHP_WEBROOT}"}"

declare -x PHP_SKIP_CHOWN
: "${PHP_SKIP_CHOWN:="false"}"

declare -x PHP_SKIP_TEMPLATES
: "${PHP_SKIP_TEMPLATES:="false"}"
