#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in ./custom.d/*.sh
  do
    source ${FILE}
  done
fi

exec /usr/sbin/php-fpm7
