#!/bin/bash

checker() {
  if [[ $1 -ne 0 ]]
  then
    /usr/bin/s6-svscanctl -t /etc/s6
  fi
}

echo "Writing php config... "
/usr/bin/templater -d -p php \
  -o /etc/php/php.ini \
  /etc/templates/php.ini.tmpl
checker $?

chown -R caddy:caddy \
  /app
