#!/bin/bash

/usr/bin/templater -d -p php \
  -o /etc/php/php.ini \
  /etc/templates/php.ini.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p php \
  -o /etc/php/php-fpm.conf \
  /etc/templates/php-fpm.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

chown -R caddy:caddy \
  /srv/www

pushd /srv/www > /dev/null
  if [ -f composer.json ]
  then
    if [ -n "${GITHUB_TOKEN}" ]
    then
      /usr/bin/gosu \
        caddy \
        /usr/bin/composer \
        config \
        -n \
        -g github-oauth.github.com \
        ${GITHUB_TOKEN}
    fi

    n=0
    until [ $n -ge 5 ]
    do
      /usr/bin/gosu \
        caddy \
        /usr/bin/composer \
        install \
        --no-dev \
        --no-scripts \
        -n \
        -q \
        --working-dir /srv/www && break

        n=$(($n+1))
        sleep 3
    done
  fi
popd > /dev/null
