FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:0f01e71f5f6079c7cdba767907024e3aa3b20e2ae6c426dfe18a4f497f57af3b

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php81 php81-phpdbg php81-fpm php81-ctype php81-curl php81-dom php81-gd php81-iconv php81-intl php81-mysqli php81-mysqlnd php81-openssl php81-opcache php81-pdo php81-pdo_mysql php81-pdo_pgsql php81-pdo_sqlite php81-pear php81-pgsql php81-phar php81-sqlite3 php81-xml php81-zip php81-mbstring php81-simplexml php81-tokenizer php81-xmlwriter php81-fileinfo php81-soap php81-pecl-apcu php81-pecl-redis php81-pecl-memcached git && \
  ln -sf /usr/bin/php81 /usr/bin/php && \
  groupadd -g 1000 php && \
  useradd -u 1000 -d /srv/www -g php -s /bin/bash -M php && \
  rm -rf /var/cache/apk/* /etc/php81/*

VOLUME ["/etc/php81/custom.d"]
EXPOSE 9000

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php81/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
