#!/bin/bash

declare -x CADDY_AGREE
declare -x CADDY_CA
declare -x CADDY_CPU
declare -x CADDY_EMAIL
declare -x CADDY_GRACE
declare -x CADDY_HTTP2
declare -x CADDY_QUIET

[[ -z "${CADDY_AGREE}" ]] && CADDY_AGREE="false"
[[ -z "${CADDY_CA}" ]] && CADDY_CA="https://acme-v01.api.letsencrypt.org/directory"
[[ -z "${CADDY_CPU}" ]] && CADDY_CPU="100%"
[[ -z "${CADDY_EMAIL}" ]] && CADDY_EMAIL=""
[[ -z "${CADDY_GRACE}" ]] && CADDY_GRACE="5s"
[[ -z "${CADDY_HTTP2}" ]] && CADDY_HTTP2="true"
[[ -z "${CADDY_QUIET}" ]] && CADDY_QUIET="false"
