FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:5eab89a3e92fb3fc34402d549e5980ab66fb84b1e2267deb2f7ab593e68fc003

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php82 php82-phpdbg php82-fpm php82-ctype php82-curl php82-dom php82-gd php82-iconv php82-intl php82-mysqli php82-mysqlnd php82-openssl php82-opcache php82-pdo php82-pdo_mysql php82-pdo_pgsql php82-pdo_sqlite php82-pear php82-pgsql php82-phar php82-sqlite3 php82-xml php82-zip php82-mbstring php82-simplexml php82-tokenizer php82-xmlwriter php82-fileinfo php82-soap php82-pecl-apcu php82-pecl-redis php82-pecl-memcached git && \
  ln -sf /usr/bin/php82 /usr/bin/php && \
  groupadd -g 1000 php && \
  useradd -u 1000 -d /srv/www -g php -s /bin/bash -M php && \
  rm -rf /var/cache/apk/* /etc/php82/*

VOLUME ["/etc/php82/custom.d"]
EXPOSE 9000

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php82/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
