#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

echo "Starting caddy!"
/usr/bin/gosu \
  caddy \
  /usr/bin/caddy \
  -conf=/etc/caddy/caddyfile
