#!/bin/bash

/usr/bin/templater -d -p php \
  -o /etc/nginx/nginx.conf \
  /etc/templates/nginc.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p php \
  -o /etc/nginx/host.conf \
  /etc/templates/host.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

chown -R nginx:nginx \
  /app \
  /var/lib/nginx
