#!/bin/bash

declare -x CONFIG_PRESET
declare -x PHP_MEMORY_LIMIT
declare -x PHP_POST_MAX_SIZE
declare -x PHP_UPLOAD_MAX_FILESIZE
declare -x PHP_MAX_EXECUTION_TIME
declare -x PHP_MAX_INPUT_TIME
declare -x PHP_DATE_TIMEZONE

find /etc/php/custom.d -mindepth 1 -type d -print0 | while read -d $'\0' TEMPLATE
do
  RELATIVENAME=${TEMPLATE//\/etc\/php\/custom.d\//}

  if [ ! -d "/etc/php/conf.d/${RELATIVENAME}" ]
  then
    mkdir "/etc/php/conf.d/${RELATIVENAME}"
  fi
done

find /etc/php/custom.d -mindepth 1 -type f -print0 | while read -d $'\0' TEMPLATE
do
  RELATIVENAME=${TEMPLATE//\/etc\/php\/custom.d\//}

  ln -sf \
    "/etc/php/conf.d/${RELATIVENAME}" \
    "/etc/php/custom.d/${RELATIVENAME}"
done

if [ -z "${PHP_MEMORY_LIMIT}" ]
then
  PHP_MEMORY_LIMIT=512M
fi

if [ -z "${PHP_POST_MAX_SIZE}" ]
then
  PHP_POST_MAX_SIZE=2G
fi

if [ -z "${PHP_UPLOAD_MAX_FILESIZE}" ]
then
  PHP_UPLOAD_MAX_FILESIZE=2G
fi

if [ -z "${PHP_MAX_EXECUTION_TIME}" ]
then
  PHP_MAX_EXECUTION_TIME=3600
fi

if [ -z "${PHP_MAX_INPUT_TIME}" ]
then
  PHP_MAX_INPUT_TIME=3600
fi

if [ -z "${PHP_DATE_TIMEZONE}" ]
then
  PHP_DATE_TIMEZONE=UTC
fi

envsubst < /etc/templates/php.ini.tmpl > /etc/php/php.ini
