#!/usr/bin/env bash

declare -x GITHUB_TOKEN
[[ -z "${GITHUB_TOKEN}" ]] && GITHUB_TOKEN=""

declare -x PHP_MEMORY_LIMIT
[[ -z "${PHP_MEMORY_LIMIT}" ]] && PHP_MEMORY_LIMIT="1G"

declare -x PHP_ERROR_REPORTING
[[ -z "${PHP_ERROR_REPORTING}" ]] && PHP_ERROR_REPORTING="E_ALL & ~E_DEPRECATED & ~E_STRICT"

declare -x PHP_DISPLAY_ERRORS
[[ -z "${PHP_DISPLAY_ERRORS}" ]] && PHP_DISPLAY_ERRORS="On"

declare -x PHP_DISPLAY_STARTUP_ERRORS
[[ -z "${PHP_DISPLAY_STARTUP_ERRORS}" ]] && PHP_DISPLAY_STARTUP_ERRORS="On"

declare -x PHP_LOG_ERRORS
[[ -z "${PHP_LOG_ERRORS}" ]] && PHP_LOG_ERRORS="On"

declare -x PHP_LOG_ERRORS_MAX_LEN
[[ -z "${PHP_LOG_ERRORS_MAX_LEN}" ]] && PHP_LOG_ERRORS_MAX_LEN="1024"

declare -x PHP_IGNORE_REPEATED_ERRORS
[[ -z "${PHP_IGNORE_REPEATED_ERRORS}" ]] && PHP_IGNORE_REPEATED_ERRORS="Off"

declare -x PHP_IGNORE_REPEATED_SOURCE
[[ -z "${PHP_IGNORE_REPEATED_SOURCE}" ]] && PHP_IGNORE_REPEATED_SOURCE="Off"

declare -x PHP_REPORT_MEMLEAKS
[[ -z "${PHP_REPORT_MEMLEAKS}" ]] && PHP_REPORT_MEMLEAKS="On"

declare -x PHP_TRACK_ERRORS
[[ -z "${PHP_TRACK_ERRORS}" ]] && PHP_TRACK_ERRORS="Off"

declare -x PHP_HTML_ERRORS
[[ -z "${PHP_HTML_ERRORS}" ]] && PHP_HTML_ERRORS="On"

declare -x PHP_POST_MAX_SIZE
[[ -z "${PHP_POST_MAX_SIZE}" ]] && PHP_POST_MAX_SIZE="2G"

declare -x PHP_UPLOAD_MAX_FILESIZE
[[ -z "${PHP_UPLOAD_MAX_FILESIZE}" ]] && PHP_UPLOAD_MAX_FILESIZE="2G"

declare -x PHP_MAX_EXECUTION_TIME
[[ -z "${PHP_MAX_EXECUTION_TIME}" ]] && PHP_MAX_EXECUTION_TIME="3600"

declare -x PHP_MAX_INPUT_TIME
[[ -z "${PHP_MAX_INPUT_TIME}" ]] && PHP_MAX_INPUT_TIME="3600"

declare -x PHP_DATE_TIMEZONE
[[ -z "${PHP_DATE_TIMEZONE}" ]] && PHP_DATE_TIMEZONE="UTC"

declare -x PHP_LOG_LEVEL
[[ -z "${PHP_LOG_LEVEL}" ]] && PHP_LOG_LEVEL="warning"

declare -x PHP_MAX_CHILDREN
[[ -z "${PHP_MAX_CHILDREN}" ]] && PHP_MAX_CHILDREN="75"

declare -x PHP_MAX_REQUESTS
[[ -z "${PHP_MAX_REQUESTS}" ]] && PHP_MAX_REQUESTS="500"

declare -x PHP_PROCESS_IDLE_TIMEOUT
[[ -z "${PHP_PROCESS_IDLE_TIMEOUT}" ]] && PHP_PROCESS_IDLE_TIMEOUT="10s"

declare -x PHP_COMPOSER_INSTALL
[[ -z "${PHP_COMPOSER_INSTALL}" ]] && PHP_COMPOSER_INSTALL="true"
