FROM webhippie/alpine:latest-amd64@sha256:909cdc67801cfb731a529a6bc8f5c2c74f84dcf34afdef74e2fdde328ce40d44

VOLUME ["/etc/php8/custom.d"]
EXPOSE 9000

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php8 php8-phpdbg php8-fpm php8-ctype php8-curl php8-dom php8-gd php8-iconv php8-intl php8-json php8-mysqli php8-mysqlnd php8-openssl php8-opcache php8-pdo php8-pdo_mysql php8-pdo_pgsql php8-pdo_sqlite php8-pear php8-pgsql php8-phar php8-sqlite3 php8-xml php8-zip php8-mbstring php8-simplexml php8-tokenizer php8-xmlwriter php8-fileinfo php8-soap php8-apcu php8-pecl-redis php8-pecl-memcached git && \
  ln -sf /usr/bin/php8 /usr/bin/php && \
  groupadd -g 1000 php && \
  useradd -u 1000 -d /srv/www -g php -s /bin/bash -M php && \
  rm -rf /var/cache/apk/* /etc/php8/*

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php8/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
