#!/usr/bin/env bash

declare -x GITHUB_TOKEN
[[ -z "${GITHUB_TOKEN}" ]] && GITHUB_TOKEN=""

declare -x PHP_MEMORY_LIMIT
[[ -z "${PHP_MEMORY_LIMIT}" ]] && PHP_MEMORY_LIMIT="1G"

declare -x PHP_POST_MAX_SIZE
[[ -z "${PHP_POST_MAX_SIZE}" ]] && PHP_POST_MAX_SIZE="2G"

declare -x PHP_UPLOAD_MAX_FILESIZE
[[ -z "${PHP_UPLOAD_MAX_FILESIZE}" ]] && PHP_UPLOAD_MAX_FILESIZE="2G"

declare -x PHP_MAX_EXECUTION_TIME
[[ -z "${PHP_MAX_EXECUTION_TIME}" ]] && PHP_MAX_EXECUTION_TIME="3600"

declare -x PHP_MAX_INPUT_TIME
[[ -z "${PHP_MAX_INPUT_TIME}" ]] && PHP_MAX_INPUT_TIME="3600"

declare -x PHP_DATE_TIMEZONE
[[ -z "${PHP_DATE_TIMEZONE}" ]] && PHP_DATE_TIMEZONE="UTC"

declare -x PHP_LOG_LEVEL
[[ -z "${PHP_LOG_LEVEL}" ]] && PHP_LOG_LEVEL="warning"

declare -x PHP_MAX_CHILDREN
[[ -z "${PHP_MAX_CHILDREN}" ]] && PHP_MAX_CHILDREN="75"

declare -x PHP_MAX_REQUESTS
[[ -z "${PHP_MAX_REQUESTS}" ]] && PHP_MAX_REQUESTS="500"

declare -x PHP_PROCESS_IDLE_TIMEOUT
[[ -z "${PHP_PROCESS_IDLE_TIMEOUT}" ]] && PHP_PROCESS_IDLE_TIMEOUT="10s"

declare -x PHP_COMPOSER_INSTALL
[[ -z "${PHP_COMPOSER_INSTALL}" ]] && PHP_COMPOSER_INSTALL="true"
